POST http://localhost:3000/create-account
Content-Type: application/json
Authorization:  

{
    "conversationId":"",
    "sender":"",
    "text":""
}

#####

GET https://letsbug-social-network.herokuapp.com/


#####

PUT http://localhost:3000/post/like/628f0410042b1d367850ed06/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODUwOWVkNDQ4MDUwYWY3YjU1YzcyNCIsIm5hbWUiOiJUYW5pc2hhIHNpbmdoIiwidXNlcm5hbWUiOiJGYXNoaW9uRGVzaWduZXIiLCJlbWFpbCI6InRhbmlzaGFAZ21haWwuY29tIiwiaWF0IjoxNjUzNTQ3ODgxLCJleHAiOjE2NTM1NTE0ODF9.H8lRvEveIpMtyHevchsad4L6uwko5X-4JDsbHYrRgGc

#####
